### ISSUE TITLE
Issue with entering raffles.

### ISSUE THREAD

**Issue by Yhteys** [Bonfire/Scraffle#4]
**I know that this plugin is probably abandoned, but I'm still going to open a issue.**

Everything in the program is working except entering raffles. When running the _.jar_ it opens different raffles, but does't join them. Every time it opens another raffle it prints "Something went wrong!"

**Comment by powaX** [comment]
For me it doesn't even say "sth went wrong"

**Comment by Bonfire** [comment]
This project is legacy and is no longer being maintained. I do not suggest using this project, as it may lead to you getting banned on the site. Closing this, as `wontfix` due to the project being legacy
